//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boss_Girls
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_to_store
    {
        public string Store_From { get; set; }
        public string Store_To { get; set; }
        public int Prod_ID { get; set; }
        public int Quantity { get; set; }
        public int Sup_ID { get; set; }
        public int Transact_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
